name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Extract Archlinux
      run: |
        docker pull archlinux/base
        docker save archlinux/base | sudo tar -xv -C /
        docker rmi archlinux/base
