name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Extract Archlinux
      run: |
        wget -O /tmp/undocker.py https://github.com/larsks/undocker/raw/c951f021e701b4ce61de03eb668a440e69646889/undocker.py
        sudo mkdir -p /rootfs
        docker pull archlinux/base
        docker save archlinux/base | sudo python3 /tmp/undocker.py -o /rootfs archlinux/base
        docker rmi archlinux/base
        rm -fr /tmp/undocker.py
        sudo sh -c 'mkdir -p /bin/ /sbin/ /usr/sbin/ /lib64/ /lib/ /usr/lib64/ ;
        cp -r /bin/* /sbin/* /usr/sbin/* /usr/bin/ ;
        cp -r /lib64/* /lib/* /usr/lib64/* /usr/lib/ ;
        rm -fr /bin/ /sbin/ /usr/sbin/ /lib64/ /lib/ /usr/lib64/ &&
        /rootfs/usr/bin/cp -r /rootfs/* /'
