name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Extract Archlinux
      run: |
        docker save archlinux/base | tar -xv -C /
