name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Extract Archlinux
      run: |
        wget -O /tmp/undocker.py https://github.com/larsks/undocker/raw/c951f021e701b4ce61de03eb668a440e69646889/undocker.py
        sudo mkdir -p /rootfs
        docker pull archlinux/base
        docker save archlinux/base | sudo python3 /tmp/undocker.py -o /rootfs archlinux/base
        docker rmi archlinux/base
        rm -fr /tmp/undocker.py
        sudo mkdir /rootfs/old.rootfs
        sudo mount --bind / /rootfs/old.rootfs
        sudo chroot /rootfs /bin/sh -c '
        cd /old.rootfs;
        cp -fr sbin/* bin/* usr/sbin/* usr/bin;
        cp -fr lib/* usr/lib;
        rm -fr sbin bin lib usr/sbin;
        ln -s usr/bin bin;
        ln -s usr/bin sbin;
        ln -s usr/bin usr/sbin;
        ln -s usr/lib lib;
        cd /;
        cp -Pfr etc home lib64 mnt opt root run sbin srv usr var /old.rootfs
        '
