name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install Archlinux
      run: curl -L https://github.com/zaoqi/github-actions-archlinux/raw/master/install.sh | sh
    - name: Test Docker
      run: |
        sudo pacman --noconfirm -Syu docker
        sudo dockerd -H unix:///var/run/docker.sock
        docker run --rm hello-world
