name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Extract Archlinux
      run: |
        wget -O /tmp/undocker.py https://github.com/larsks/undocker/raw/c951f021e701b4ce61de03eb668a440e69646889/undocker.py
        sudo mkdir -p /rootfs
        docker pull archlinux/base
        docker save archlinux/base | sudo python3 /tmp/undocker.py -o /rootfs archlinux/base
        docker rmi archlinux/base
        rm -fr /tmp/undocker.py
        sudo sh -c "
        systemctl stop docker
        mkdir /rootfs/old.rootfs
        mount --bind / /rootfs/old.rootfs
        chroot /rootfs /bin/sh -c '
        cd /old.rootfs &&
        rm -fr sbin bin lib usr lib64 var/mail var/spool/mail &&
        cd /old.rootfs/etc/ &&
        cp -Pfr passwd group shadow hosts resolv.conf hostname sudoers sudoers.d /etc/ &&
        cd / &&
        cp -Pfr bin etc home lib lib64 mnt opt root run sbin srv usr var /old.rootfs
        ' &&
        umount /rootfs/old.rootfs &&
        rm -fr /rootfs/ &&
        pacman --noconfirm --force -Syu gzip pacman sed systemd base sudo docker git
        "
